language: android
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/3.3
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - chmod +x gradlew

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by the project
    - build-tools-28.0.3

    # The SDK version used to compile the project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-23
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - android-23
    - sys-img-armeabi-v7a-android-23
    #- sys-img-x86-android-28

script:
  - ./gradlew clean
  - ./gradlew assembleDebug
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do sleep 1; done
  - adb shell input keyevent 82 &
  - ./gradlew jacocoTestReportDebug

after_success:
  - bash <(curl -s https://codecov.io/bash)

#after_failure:
#  - wget http://imgur.com/tools/imgurbash.sh
#  - chmod a+x imgurbash.sh
#  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
#  - ./imgurbash.sh screen.png
#  - pandoc weather-app-demo/weather-app/build/reports/tests/release/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
